---
title: "cfb_prediction_model"
author: "Anthony Fernandez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("cfbfastR")
#install.packages("dplyr")
#install.packages("caret")
#install.packages("e1071")
#install.packages("xgboost")
#install.packages("randomForest")
#install.packages("zoo")
library(zoo)
library(caret)
library(dplyr)
library(cfbfastR)
library(xgboost)
library(randomForest)
library(reshape2)
library(ggplot2)
```




```{r}



cfb_data <- load_cfb_pbp(2018:2024)

fbs_conf = c("ACC", "SEC", "Pac-12", "Big 12", "Big Ten", "Sun Belt", "Conference USA", "FBS Independents", "Mountain West", "American Athletic")

cfb_data <- cfb_data %>% filter((offense_conference %in% fbs_conf | defense_conference %in% fbs_conf))


```



```{r  betting}

bet_added <- function() {
  
  
  years <- 2018:2024
  lines = cfbd_betting_lines(year = years[1])
  for (y in years[-1]){
    print(y)
    lines <- rbind(lines, cfbd_betting_lines(year = y))
  }
  
   filtered <- lines %>% mutate(bet_winner = gsub("[^a-zA-Z ]", "", formatted_spread)) %>% select(game_id, bet_winner, provider) %>% distinct() %>% group_by(game_id) %>% pivot_wider(names_from = provider, values_from = bet_winner) %>% select(teamrankings, numberfire, consensus, Caesars) 
  
  # summarised <- lines %>% na.omit() %>% rowwise() %>%
  #   mutate(ml_correct = ifelse(min(home_moneyline, away_moneyline) == home_moneyline && (home_score > away_score), 1, 0)) %>%
  #   group_by(provider) %>% summarise(acc_provider = mean(ml_correct))
  # 
  # 
  # betting <- lines %>% select(game_id, home_moneyline, away_moneyline, provider) %>% inner_join(summarised) %>% select(-provider)
  # return(betting)
  calculate_mode <- function(x) { ux <- unique(x) 
  ux[which.max(tabulate(match(x, ux)))] }



game_ids = filtered %>% select(game_id)
df <- filtered %>% ungroup() %>% select(-game_id)


df <- df %>% rowwise() %>%
  mutate(teamrankings = ifelse(is.na(teamrankings), calculate_mode(c(numberfire, consensus, Caesars) %>% na.omit()), teamrankings))%>%
  mutate(consensus = ifelse(is.na(consensus), calculate_mode(c(numberfire, teamrankings, Caesars) %>% na.omit()), consensus))%>%
 mutate(numberfire = ifelse(is.na(numberfire), calculate_mode(c(teamrankings, consensus, Caesars) %>% na.omit()), numberfire))%>%
  mutate(Caesars = ifelse(is.na(Caesars), calculate_mode(c(numberfire, consensus, teamrankings) %>% na.omit()), Caesars))
 
return(cbind(game_ids, df))
}


# weather_added <- function(){
#   years <- 2018:2024
#   
#   weather = cfbd_game_weather(year = 2018,
#   season_type = "regular")
#   
#   for (y in years[-1]){
#     print(y)
#     weather <- rbind(weather, cfbd_game_weather(year = y,
#   season_type = "regular"))
#   }
#   
#   weather <- weather %>% select(game_id, game_indoors, temperature, humidity, precipitation, snowfall, wind_speed)
#   return(weather)
# }
# 
# weather_added()

# in_game_metrics <- function(){
#   
#   box_stats = cfbd_game_box_advanced(unique(cfb_data$game_id)[1])
# 
#   count = 0
# #  for (i in unique(cfb_data$game_id)[-1]){
# #   print(count)
# #    box_stats <- rbind(box_stats, cfbd_game_box_advanced(i))
# #    count = count+1
# #  }
#   
#   game_ids = rep(unique(cfb_data$game_id), each = 2)
#   box_stats = cbind(game_ids, box_stats)
#   return(box_stats)
# }

talent_rankings <- function(){
  
  years <- 2018:2024
  talent = cfbd_team_talent(year = years[1])
  for (y in years[-1]){
    print(y)
    talent <- rbind(talent, cfbd_team_talent(year = y))
  }
  
  talent$home_talent = talent$talent
  talent <- talent %>% rename(away_talent = talent)
  return(talent)
}




```

```{r}
library(tidyr)
# Function to aggregate game-level data and merge past stats for both teams
aggregate_game_data <- function(pbp_data, window = 6 , betting_bool) {
  
  # Extract final score from the last row of each game
  final_scores <- pbp_data %>%
    group_by(game_id) %>%
    filter(row_number() == n()) %>%  # Select the last row for each game
    summarise(
      pos_team_final_score = pos_team_score,  # Final score for the pos_team
      def_team_final_score = def_pos_team_score,  # Final score for the def_pos_team
      pos_team = last(pos_team),  # Last team in possession
      def_pos_team = last(def_pos_team),  # Last team defending
      home = last(home),
      away = last(away),
      week = last(week),
      year = last(year)
    ) %>%
    ungroup()

  if(betting_bool){
      #Add bet
  betting <- bet_added()
  final_scores <- final_scores %>% inner_join(betting, by = "game_id")
  }

  
  talent <- talent_rankings()
  talent$year <- as.numeric(talent$year)
  final_scores <- final_scores %>% inner_join(talent[,c(1,2,4)], by = c("home"= "school","year"= "year"))
  final_scores <- final_scores %>% inner_join(talent[,c(1,2,3)], by = c("away"= "school","year"= "year"))


  pbp_data1 <- pbp_data %>% mutate(success = case_when( down == 1 & yards_gained >= 0.5 * yards_to_goal ~ 1, down == 2 & yards_gained >= 0.7 * yards_to_goal ~ 1, down == 3 & yards_gained >= yards_to_goal ~ 1, down == 4 & yards_gained >= yards_to_goal ~ 1, TRUE ~ 0 ))
  
  
  
  # Summarize past stats for each team
  team_stats <- pbp_data1 %>%
    filter(!is.na(EPA)) %>%
    group_by(year, pos_team, week) %>%
    summarise(
      epa_per_play = mean(EPA, na.rm = TRUE),
      epa_per_pass = mean(EPA[play_type %in% c("Pass", "Pass Incompletion",  "Pass Reception", "Passing Touchdown" )], na.rm = TRUE),
      epa_per_rush = mean(EPA[play_type %in% c("Rush", "Rushing Touchdown")], na.rm = TRUE),
      wpa_per_play = mean(wpa, na.rm = TRUE),
      success_rate = sum(success)/n()
      
      
    ) %>%
    ungroup()
  
  # Add rolling averages (past `window` games) for each team
  team_stats <- team_stats %>%
    group_by(pos_team, year) %>%
    arrange(week) %>%
    mutate(
      epa_per_play_last_n = zoo::rollapplyr(epa_per_play, window, mean, na.rm = TRUE, fill = NA, align = 'right'),
      epa_per_pass_last_n = zoo::rollapplyr(epa_per_pass, window, mean,na.rm = TRUE, fill = NA, align = 'right'),
      epa_per_rush_last_n = zoo::rollapplyr(epa_per_rush, window, mean,na.rm = TRUE, fill = NA, align = 'right'),
      wpa_per_play_last_n = zoo::rollapplyr(wpa_per_play, window, mean,na.rm = TRUE, fill = NA, align = 'right'),
      success_rate_last_n =zoo::rollapplyr(success_rate, window, mean,na.rm = TRUE, fill = NA, align = 'right')
    ) %>%
    ungroup()
  
  summary(team_stats$epa_per_pass)
  
  #rolling averages for quartely data 

  # Merge stats for both teams in each game
  game_data <- final_scores %>%
    left_join(team_stats, by = c("year", "pos_team", "week")) %>%
    rename_with(~ paste0("pos_team_", .), starts_with("epa_")) %>%
    rename_with(~ paste0("pos_team_", .), starts_with("wpa_")) %>%
    rename_with(~ paste0("pos_team_", .), starts_with("success_") )%>%
    left_join(team_stats, by = c("year", "def_pos_team" = "pos_team", "week")) %>%
    rename_with(~ paste0("def_team_", .), starts_with("epa_")) %>%
    rename_with(~ paste0("def_team_", .), starts_with("wpa_")) %>%
  rename_with(~ paste0("def_team_", .), starts_with("success_") )

  
  
  return(game_data)
}

```



```{r eval = false}
# Create stratified folds

set.seed(2)
processed <- aggregate_game_data(cfb_data)
trainIndex <- createDataPartition(processed$home, p = 0.6, list = FALSE)
season_level_data_train <- processed[trainIndex, ]
season_level_data_test <- processed[-trainIndex, ]

# Further split temp_data into validation and test sets
valIndex <- createDataPartition(season_level_data_test$home, p = 0.5, list = FALSE)
season_level_data_test <- season_level_data_test[valIndex, ]
season_level_data_predict <- season_level_data_test[-valIndex, ]


season_level_data_train
season_level_data_test
season_level_data_predict

```


```{r ROUND 1 MODEL}

season_level_data_train = aggregate_game_data(cfb_data,6, TRUE)
season_level_data_train <- season_level_data_train %>%
  mutate(
    home_team_epa_per_play_last_n = ifelse(home == pos_team, pos_team_epa_per_play_last_n, def_team_epa_per_play_last_n),
    home_team_epa_per_pass_last_n = ifelse(home == pos_team, pos_team_epa_per_pass_last_n, def_team_epa_per_pass_last_n),
    home_team_epa_per_rush_last_n = ifelse(home == pos_team, pos_team_epa_per_rush_last_n, def_team_epa_per_rush_last_n),
    home_team_wpa_per_play_last_n = ifelse(home == pos_team, pos_team_wpa_per_play_last_n, def_team_wpa_per_play_last_n),
    home_team_success_rate_last_n = ifelse(home == pos_team, pos_team_success_rate_last_n, def_team_success_rate_last_n),
    away_team_epa_per_play_last_n = ifelse(away == pos_team, pos_team_epa_per_play_last_n, def_team_epa_per_play_last_n),
    away_team_epa_per_pass_last_n = ifelse(away == pos_team, pos_team_epa_per_pass_last_n, def_team_epa_per_pass_last_n),
    away_team_epa_per_rush_last_n = ifelse(away == pos_team, pos_team_epa_per_rush_last_n, def_team_epa_per_rush_last_n),
    away_team_wpa_per_play_last_n = ifelse(away == pos_team, pos_team_wpa_per_play_last_n, def_team_wpa_per_play_last_n),
    away_team_success_rate_last_n = ifelse(away == pos_team, pos_team_success_rate_last_n, def_team_success_rate_last_n)

  )

season_level_data_train <- na.omit(season_level_data_train)

season_level_data_train$home_team_final_score <- ifelse(season_level_data_train$home == season_level_data_train$pos_team, season_level_data_train$pos_team_final_score, season_level_data_train$def_team_final_score)

season_level_data_train$away_team_final_score <- ifelse(season_level_data_train$away == season_level_data_train$pos_team, season_level_data_train$pos_team_final_score, season_level_data_train$def_team_final_score)

season_level_data_train$home_away_score_dif <- (season_level_data_train$home_team_final_score - season_level_data_train$away_team_final_score)
  
#train_dat <- season_level_data_train[, c(6:8, 10:13, 26:33,37)]
selected_cols <- c("home", "away", "week", "teamrankings", "numberfire", 
                   "consensus", "Caesars", "home_team_epa_per_play_last_n", 
                   "home_team_epa_per_pass_last_n", "home_team_epa_per_rush_last_n", 
                   "home_team_wpa_per_play_last_n", "away_team_epa_per_play_last_n", 
                   "away_team_epa_per_pass_last_n", "away_team_epa_per_rush_last_n", 
                   "away_team_wpa_per_play_last_n", "home_away_score_dif" , "away_team_success_rate_last_n", "home_team_success_rate_last_n" ,"home_talent", "away_talent")


# #selected_cols <- c("home", "away", "week", "home_team_epa_per_play_last_n", 
#                    "home_team_epa_per_pass_last_n", "home_team_epa_per_rush_last_n", 
#                    "home_team_wpa_per_play_last_n", "away_team_epa_per_play_last_n", 
#                    "away_team_epa_per_pass_last_n", "away_team_epa_per_rush_last_n", 
#                    "away_team_wpa_per_play_last_n", "home_away_score_dif" , "home_talent", "away_talent")

train_dat <- season_level_data_train %>% select(all_of(selected_cols))

train_dat <- data.frame(train_dat) %>%  mutate(consensus = ifelse(trimws(consensus) == home ,1, 0),
                    teamrankings = ifelse(trimws(teamrankings) == home,1, 0),
                    Caesars = ifelse(trimws(Caesars) == home,1,0),
                    numberfire = ifelse(trimws(numberfire) == home, 1, 0))

train_dat

model <- randomForest(home_away_score_dif ~ ., 
                      data = train_dat,
                      importance =TRUE
                      )
moneylines <- readxl::read_excel("C:/Users/immim/Downloads/Money Line (1).xlsx")

moneylines = moneylines %>% select(-c(`Home Team Money Line` ,`Away Team Money Line`, away) ) %>% pivot_wider(names_from = Website, values_from = winner) 


home <- data.frame( home = c("Notre Dame", "Texas", "Ohio State", "Penn State"))

away <- data.frame(away = c("Indiana", "Clemson", "Tennessee", "SMU"))

df2 <- inner_join(team_to_pred, home, by = c("team" = "home")) %>% mutate(num = c(1,2,3,4))


df2 <- df2 %>%
    rename_with(~ paste0("home_", .), starts_with("team")) %>% rename( home = home_team, home_talent= talent) %>% select(-week)

df3 <- inner_join(team_to_pred, away, by = c("team" = "away")) %>% mutate(num = c(1,3,4,2))


df3 <- df3 %>%
    rename_with(~ paste0("away_", .), starts_with("team")) %>% rename( away = away_team, away_talent= talent)


df_final <- inner_join(df2, df3, by ="num") %>% select(-num)
df_final <- inner_join(df_final, moneylines, by ="home") 


df_final <- data.frame(df_final) %>%  mutate(consensus = ifelse(trimws(consensus) == home ,1, 0),
                    teamrankings = ifelse(trimws(teamrankings) == home,1, 0),
                    Caesars = ifelse(trimws(Caesars) == home,1,0),
                    numberfire = ifelse(trimws(numberfire) == home, 1, 0))

prediction <- predict(model, df_final)

round0 = t(rbind(df_final$home, df_final$away, prediction) ) 
colnames(round0) = c("winner","against", "win_margin")

rows = c(row.names(var_importance))
var_importance <- data.frame(importance(model) ) %>% arrange(desc(X.IncMSE)) %>% head(7) %>% select(-IncNodePurity)
knitr::kable(var_importance)

knitr::kable(round0)

```



```{r mutate func}
mutate_data <- function(processed){

dat <- processed %>%
  mutate(
    home_team_epa_per_play_last_n = ifelse(home == pos_team, pos_team_epa_per_play_last_n, def_team_epa_per_play_last_n),
    home_team_epa_per_pass_last_n = ifelse(home == pos_team, pos_team_epa_per_pass_last_n, def_team_epa_per_pass_last_n),
    home_team_epa_per_rush_last_n = ifelse(home == pos_team, pos_team_epa_per_rush_last_n, def_team_epa_per_rush_last_n),
    home_team_wpa_per_play_last_n = ifelse(home == pos_team, pos_team_wpa_per_play_last_n, def_team_wpa_per_play_last_n),
    home_team_success_rate_last_n = ifelse(home == pos_team, pos_team_success_rate_last_n, def_team_success_rate_last_n),
    away_team_epa_per_play_last_n = ifelse(away == pos_team, pos_team_epa_per_play_last_n, def_team_epa_per_play_last_n),
    away_team_epa_per_pass_last_n = ifelse(away == pos_team, pos_team_epa_per_pass_last_n, def_team_epa_per_pass_last_n),
    away_team_epa_per_rush_last_n = ifelse(away == pos_team, pos_team_epa_per_rush_last_n, def_team_epa_per_rush_last_n),
    away_team_wpa_per_play_last_n = ifelse(away == pos_team, pos_team_wpa_per_play_last_n, def_team_wpa_per_play_last_n),
    away_team_success_rate_last_n = ifelse(away == pos_team, pos_team_success_rate_last_n, def_team_success_rate_last_n)
  )

dat <- na.omit(dat)

dat$home_team_final_score <- ifelse(dat$home == dat$pos_team, dat$pos_team_final_score, dat$def_team_final_score)

dat$away_team_final_score <- ifelse(dat$away == dat$pos_team, dat$pos_team_final_score, dat$def_team_final_score)

dat$home_away_score_dif <- (dat$home_team_final_score - dat$away_team_final_score)

dat <- dat %>% mutate(home_win = ifelse(home_away_score_dif < 0, 0, 1)) %>% select(-home_away_score_dif) #logistic home win outcome


selected_cols <- c("home", "away", "week",  "home_team_epa_per_play_last_n", 
                   "home_team_epa_per_pass_last_n", "home_team_epa_per_rush_last_n", 
                   "home_team_wpa_per_play_last_n", "away_team_epa_per_play_last_n", 
                   "away_team_epa_per_pass_last_n", "away_team_epa_per_rush_last_n", 
                   "away_team_wpa_per_play_last_n","away_team_success_rate_last_n", "home_team_success_rate_last_n" ,"home_win" , "home_talent", "away_talent")


# Select only the first two columns for dummy variables
categorical_features <- dat %>% select(all_of(selected_cols)) %>% select(home, away)

# 
# # Select only the first two columns for dummy variables
# categorical_features <- season_level_data_train %>% select(all_of(selected_cols)) %>% select(home, away, teamrankings,numberfire, consensus, Caesars)

# Create dummy variables
dummy_model <- dummyVars("~ .", data = categorical_features)
categorical_dummy <- predict(dummy_model, newdata = categorical_features)

# # Combine the rest of the columns
# numerical_features <-season_level_data_train %>% select(all_of(selected_cols))  %>% select(-c(home, away, teamrankings,numberfire, consensus, Caesars))

# Combine the rest of the columns
numerical_features <-dat %>% select(all_of(selected_cols))  %>% select(-c(home, away))


# Combine categorical and numerical features
features <- cbind(categorical_dummy, numerical_features) %>% select(-home_win)
features <- features[, c(xgb_model_log$feature_names)]

# Extract target variable
target <- dat$home_win

# Convert data to matrix
features_matrix <- as.matrix(features)
target_vector <- as.numeric(target)

# Create DMatrix
dat <- xgb.DMatrix(data = features_matrix, label = target_vector)
return(dat)
}


```

```{r mutate func 1}
mutate_data1 <- function(dat){

dat <- na.omit(dat)


selected_cols <- c("home", "away", "week",  "home_team_epa_per_play_last_n", 
                   "home_team_epa_per_pass_last_n", "home_team_epa_per_rush_last_n",
                   "home_team_wpa_per_play_last_n", "away_team_epa_per_play_last_n",
                   "away_team_epa_per_pass_last_n", "away_team_epa_per_rush_last_n",
                   "away_team_wpa_per_play_last_n","home_team_success_rate_last_n","away_team_success_rate_last_n",  "home_talent", "away_talent")

# Select only the first two columns for dummy variables
categorical_features <- dat %>% select(all_of(selected_cols)) %>% select(home, away)

# 
# # Select only the first two columns for dummy variables
# categorical_features <- season_level_data_train %>% select(all_of(selected_cols)) %>% select(home, away, teamrankings,numberfire, consensus, Caesars)

# Create dummy variables
dummy_model <- dummyVars("~ .", data = categorical_features)
categorical_dummy <- predict(dummy_model, newdata = categorical_features)

# # Combine the rest of the columns
# numerical_features <-season_level_data_train %>% select(all_of(selected_cols))  %>% select(-c(home, away, teamrankings,numberfire, consensus, Caesars))

# Combine the rest of the columns
numerical_features <-dat %>% select(all_of(selected_cols))  %>% select(-c(home, away))


# Combine categorical and numerical features
features <- cbind(categorical_dummy, numerical_features) 



for (col in c(setdiff(xgb_model_log$feature_names, colnames(features)))) { 
  features[[col]] <- 0 
}

features <- features[, c(xgb_model_log$feature_names)]


# Convert data to matrix
features_matrix <- as.matrix(features)

# Create DMatrix
dat <- xgb.DMatrix(data = features_matrix)
return(dat)
}
```

```{r}
mutate_data2 <- function(dat){

dat <- na.omit(dat)


selected_cols <-  c("home", "away", "week",  "home_team_epa_per_play_last_n", 
                   "home_team_epa_per_pass_last_n", "home_team_epa_per_rush_last_n",
                   "home_team_wpa_per_play_last_n", "away_team_epa_per_play_last_n",
                   "away_team_epa_per_pass_last_n", "away_team_epa_per_rush_last_n",
                   "away_team_wpa_per_play_last_n","home_team_success_rate_last_n","away_team_success_rate_last_n",  "home_talent", "away_talent")
# Select only the first two columns for dummy variables
categorical_features <- dat %>% select(all_of(selected_cols)) %>% select(home, away)

# 
# # Select only the first two columns for dummy variables
# categorical_features <- season_level_data_train %>% select(all_of(selected_cols)) %>% select(home, away, teamrankings,numberfire, consensus, Caesars)

# # Combine the rest of the columns
# numerical_features <-season_level_data_train %>% select(all_of(selected_cols))  %>% select(-c(home, away, teamrankings,numberfire, consensus, Caesars))

# Combine the rest of the columns
numerical_features <-dat %>% select(all_of(selected_cols))  %>% select(-c(home, away))

categorical_dummy = data.frame(homeNotreDame = 0, awayNotreDame = 1, homeOregon = 1, awayOregon =0)
# Combine categorical and numerical features
features <- cbind(categorical_dummy, numerical_features) 



for (col in c(setdiff(xgb_model_log$feature_names, colnames(features)))) { 
  features[[col]] <- 0 
}

features <- features[, c(xgb_model_log$feature_names)]


# Convert data to matrix
features_matrix <- as.matrix(features)

# Create DMatrix
dat <- xgb.DMatrix(data = features_matrix)
return(dat)
}
```




```{r xgb logistic}
# 
# season_level_data_train <- season_level_data_train %>% mutate(home_win = ifelse(home_away_score_dif < 0, 0, 1)) %>% select(-home_away_score_dif) #logistic home win outcome
# season_level_data_test <- season_level_data_test %>% mutate(home_win = ifelse(home_away_score_dif < 0, 0, 1)) %>% select(-home_away_score_dif)

pred_processed = cfb_data[cfb_data$year==2024,]
processed = cfb_data[cfb_data$year!=2024,]
processed <- aggregate_game_data(processed, 6, FALSE)
pred_processed <- aggregate_game_data(pred_processed, 6, FALSE)
pred_processed <- pred_processed %>% filter(home != "Kennesaw State" & away != "Kennesaw State")

dat <- mutate_data(processed)


params <- list(
  objective = "binary:logistic", # Set objective
              eval_metric = "auc", # Set evaluation metric to use
              eval_metric = "error", # Set evaluation metric to use
  eta = 0.1
)

xgb_model_log <- xgb.train(
  params = params,
  nrounds=1000,
  early_stopping_rounds = 50,
  data = dat,
  watchlist = list(train = dat),
  verbose = 1
)

pred_dat <-  mutate_data(pred_processed)

preds_prob <- predict(xgb_model_log, pred_dat)


for (x in seq(0.3, 0.5, by =0.01)){
  print(x)
  preds_log <- ifelse(preds_prob <= x, 0, 1)

  actual_values <- getinfo(pred_dat, "label")
  
  # Create a confusion matrix
  confusion <- confusionMatrix(as.factor(preds_log), as.factor(actual_values))
  print(confusion$overall['Accuracy'])


}
  
  preds_log <- ifelse(preds_prob <= 0.39, 0, 1)
  actual_values <- getinfo(pred_dat, "label")
  confusion <- confusionMatrix(as.factor(preds_log), as.factor(actual_values))
  print(confusion$overall['Accuracy'])
  
  
  full_dat <- aggregate_game_data(cfb_data, 6, FALSE)
  dat <- mutate_data(full_dat)

  xgb_model_log <- xgb.train(
  params = params,
  nrounds=1000,
  early_stopping_rounds = 50,
  data = dat,
  watchlist = list(train = dat),
  verbose = 1
)
  
```

```{r playoff preds}
playoffs <- aggregate_game_data(cfb_data, 6, FALSE)
cfp_teams <- c("Oregon", "Georgia", "Boise State", "Arizona State", "Texas", "Penn State", 
               "Notre Dame", "Ohio State", "Tennessee", "Indiana", "SMU", "Clemson")



playoff_to_pred <- playoffs %>% filter(week == 14) %>% filter(year==2024)
playoff_to_pred <- playoff_to_pred %>% filter(home %in% cfp_teams | away %in% cfp_teams)


team_to_pred <- playoff_to_pred %>%  mutate(team = ifelse(pos_team %in% cfp_teams, pos_team, def_pos_team)) %>% mutate(
    team_epa_per_play_last_n = ifelse(pos_team %in% cfp_teams, pos_team_epa_per_play_last_n, def_team_epa_per_play_last_n),
    team_epa_per_pass_last_n = ifelse(pos_team %in% cfp_teams, pos_team_epa_per_pass_last_n, def_team_epa_per_pass_last_n),
    team_epa_per_rush_last_n = ifelse(pos_team %in% cfp_teams, pos_team_epa_per_rush_last_n, def_team_epa_per_rush_last_n),
    team_wpa_per_play_last_n = ifelse(pos_team %in% cfp_teams, pos_team_wpa_per_play_last_n, def_team_wpa_per_play_last_n),
    team_success_rate_last_n = ifelse(pos_team %in% cfp_teams, pos_team_success_rate_last_n, def_team_success_rate_last_n),

    talent = ifelse(home %in% cfp_teams, home_talent, away_talent) 
  ) %>% select(team, team_epa_per_play_last_n,  team_epa_per_pass_last_n, team_epa_per_rush_last_n, team_wpa_per_play_last_n, team_success_rate_last_n, talent, week)

#BAsed on prev round 1
##############################################################
#round 2

home <- data.frame( home = c("Arizona State", "Oregon", "Boise State", "Georgia"))

away <- data.frame(away = c("Texas", "Ohio State", "Penn State", "Notre Dame"))

df2 <- inner_join(team_to_pred, home, by = c("team" = "home")) %>% mutate(num = c(1,2,3,4))


df2 <- df2 %>%
    rename_with(~ paste0("home_", .), starts_with("team")) %>% rename( home = home_team, home_talent= talent) %>% select(-week)

df3 <- inner_join(team_to_pred, away, by = c("team" = "away")) %>% mutate(num = c(3,4,2,1))


df3 <- df3 %>%
    rename_with(~ paste0("away_", .), starts_with("team")) %>% rename( away = away_team, away_talent= talent)

df_final <- inner_join(df2, df3, by ="num") %>% select(-num)

dat_final <- mutate_data1(df_final)




final_preds2 <- predict(xgb_model_log, dat_final)
preds_log2 <- ifelse(final_preds2 <= threshold, 0, 1)

round2 <- data.frame(rbind(home = df_final$home, away = df_final$away, home_win_prob = final_preds2, home_win = preds_log2)) %>% t()
row.names(round2) = NULL
round2
knitr::kable(round2)

```


```{r}
###############################
#round 3


home <- data.frame( home = c("Boise State", "Oregon"))

away <- data.frame(away = c("Notre Dame", "Texas"))

df2 <- inner_join(team_to_pred, home, by = c("team" = "home")) %>% mutate(num = c(1,2))


df2 <- df2 %>%
    rename_with(~ paste0("home_", .), starts_with("team")) %>% rename( home = home_team, home_talent= talent) %>% select(-week)

df3 <- inner_join(team_to_pred, away, by = c("team" = "away")) %>% mutate(num = c(1,2))


df3 <- df3 %>%
    rename_with(~ paste0("away_", .), starts_with("team")) %>% rename( away = away_team, away_talent= talent)

df_final <- inner_join(df2, df3, by ="num") %>% select(-num)

dat_final <- mutate_data1(df_final)





final_preds3 <- predict(xgb_model_log, dat_final)
preds_log3 <- ifelse(final_preds3 <= threshold, 0, 1)

round3 <-data.frame(rbind(home = df_final$home, away = df_final$away, home_win_prob = final_preds3, home_win = preds_log3)) %>% t()
row.names(round3) = NULL
round3

knitr::kable(round3)
```

```{r}
##########################3333
#round 4
home <- data.frame( home = c("Oregon"))

away <- data.frame(away = c("Notre Dame"))

df2 <- inner_join(team_to_pred, home, by = c("team" = "home")) %>% mutate(num = c(1))


df2 <- df2 %>%
    rename_with(~ paste0("home_", .), starts_with("team")) %>% rename( home = home_team, home_talent= talent) %>% select(-week)

df3 <- inner_join(team_to_pred, away, by = c("team" = "away")) %>% mutate(num = c(1))


df3 <- df3 %>%
    rename_with(~ paste0("away_", .), starts_with("team")) %>% rename( away = away_team, away_talent= talent)

df_final <- inner_join(df2, df3, by ="num") %>% select(-num)

dat_final <- mutate_data2(df_final)

final_preds4 <- predict(xgb_model_log, dat_final)
preds_log4 <- ifelse(final_preds4 <= threshold, 0, 1)

round4 <- data.frame(rbind(home = df_final$home, away = df_final$away, home_win_prob = final_preds4, home_win = preds_log4)) %>% t()
row.names(round4) = NULL
round4

knitr::kable(round4)


xgb.plot.importance(importance_matrix %>% head(5))
print(importance_matrix)
```